In [2]:
import tensorflow as tf
import tensorflow.keras as krs
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten

In [3]:
from tensorflow.python.client import device_lib 
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 1983395482161263347
 xla_global_id: -1,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 1755224475
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 7089765089861694819
 physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6"
 xla_global_id: 416903419]

In [4]:
print("Ver : "+str(tf.__version__))

Ver : 2.10.0


In [5]:
di = np.array([1,2,3])
dt = np.array([10,20,30])

In [6]:
print(di)
print(dt)

[1 2 3]
[10 20 30]


In [7]:
model = Sequential()

In [8]:
model.add(Flatten(input_shape=(1,)))
model.add(Dense(1,activation='linear'))

In [9]:
model.compile(optimizer=krs.optimizers.SGD(learning_rate=1e-2),loss='mse')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 1)                 0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.fit(di,dt,epochs=1000,verbose=2)

Epoch 1/1000
1/1 - 0s - loss: 0.0197 - 5ms/epoch - 5ms/step
Epoch 2/1000
1/1 - 0s - loss: 0.0196 - 0s/epoch - 0s/step
Epoch 3/1000
1/1 - 0s - loss: 0.0195 - 11ms/epoch - 11ms/step
Epoch 4/1000
1/1 - 0s - loss: 0.0194 - 5ms/epoch - 5ms/step
Epoch 5/1000
1/1 - 0s - loss: 0.0193 - 3ms/epoch - 3ms/step
Epoch 6/1000
1/1 - 0s - loss: 0.0192 - 3ms/epoch - 3ms/step
Epoch 7/1000
1/1 - 0s - loss: 0.0191 - 5ms/epoch - 5ms/step
Epoch 8/1000
1/1 - 0s - loss: 0.0190 - 3ms/epoch - 3ms/step
Epoch 9/1000
1/1 - 0s - loss: 0.0189 - 4ms/epoch - 4ms/step
Epoch 10/1000
1/1 - 0s - loss: 0.0188 - 3ms/epoch - 3ms/step
Epoch 11/1000
1/1 - 0s - loss: 0.0187 - 3ms/epoch - 3ms/step
Epoch 12/1000
1/1 - 0s - loss: 0.0186 - 3ms/epoch - 3ms/step
Epoch 13/1000
1/1 - 0s - loss: 0.0185 - 3ms/epoch - 3ms/step
Epoch 14/1000
1/1 - 0s - loss: 0.0185 - 3ms/epoch - 3ms/step
Epoch 15/1000
1/1 - 0s - loss: 0.0184 - 4ms/epoch - 4ms/step
Epoch 16/1000
1/1 - 0s - loss: 0.0183 - 3ms/epoch - 3ms/step
Epoch 17/1000
1/1 - 0s - loss: 0.

In [12]:
rist = model.predict(np.array([5,7,100]))

1/1 [==============================] - 0s 61ms/step


In [13]:
print(rist)

[[ 49.95999]
 [ 69.93064]
 [998.5661 ]]
